package rules;

import com.sbnz.model.*;
global Wine foundWine;



rule "Korisnik je izabrao Italijansku kuhinju i narucuje desert"
	agenda-group "prva_grupa_pravila"
	when
		$a:Answers(ethnicity == "Italijanska", haveDessert == "Da")
		$w: Wine(name == "Riesling" )
	then	
		$w.setDessert(true);
		System.out.println("Korisnik narucuje desert "+ $w.getName());
		drools.getKnowledgeRuntime().setGlobal("foundWine", $w);
end


rule "Korisnik izabrao Italijansku kuhinju i ne trenira"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Italijanska", healthConscious == "Ne")
		$m: Meat(name == "Junece meso")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());

end	


rule "Korisnik je izabarao Italijansku kuhinju, trenira i restoran kraj obale"
	agenda-group "prva_grupa_pravila"
	salience 100  
	when
		$a:Answers(ethnicity == "Italijanska", healthConscious == "Da", onTheCoast == "Da")
		
	then
		Found f = new Found();
		f.setFoundMeat("Skoljke");
		insert(f);
		System.out.println("Meso je: " + f.getFoundMeat());
		
end

rule "Korisnik je izabarao Italijansku kuhinju, trenira i restoran NIJE kraj obale"
	agenda-group "prva_grupa_pravila"
    salience 100
	when
		$a:Answers(ethnicity == "Italijanska", healthConscious == "Da", onTheCoast == "Ne")
		
	then
		Found f = new Found();
		f.setFoundMeat("Piletina");
		insert(f);
		System.out.println("Meso je: "+ f.getFoundMeat());
		
end

rule "Korisnik je izabrao Italijanksku kuhinju, intolerantan na laktozu "
	agenda-group "prva_grupa_pravila"

	when
		$a: Answers(ethnicity == "Italijanska", lactoseIntolerant == "Da")
		$f: Found()
		
	then
		$f.setFoundSauce("Tomato Paradajz");
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Italijanksku kuhinju, tolerantan na laktozu i leto je  "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Italijanska", lactoseIntolerant == "Ne", summer == "Da" )
		$f: Found()
		
	then
		$f.setFoundSauce("Tomato Paradajz");
		System.out.println("A sad je sosiiic : " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Italijanksku kuhinju, tolerantan na laktozu i nije leto "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Italijanska", lactoseIntolerant == "Ne", summer == "Ne" )
		$f: Found()
		
	then
		$f.setFoundSauce("Pavlaka");
		System.out.println("Sosic je kad nije leto : "+ $f.getFoundSauce());
end

rule "Korisnik je izabrao Italijanksku kuhinju i voli zacinjenu hranu  "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Italijanska", savoryFood =="Da" )
		$f: Found()
		
	then
		$f.getFoundSpices().add("Origano");
		$f.getFoundSpices().add("Bosiljak");
		System.out.println("Lista zacina iz pravila izmenjeno: " + $f.getFoundSpices());	
end

rule "Korisnik je izabrao Italijanksku kuhinju i ne ide na dejt "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Italijanska", onDate =="Ne" )
		$f: Found()
		
	then
		$f.getFoundSpices().add("Beli luk");
		System.out.println("Lista zacina kad ne ide na dejt: " + $f.getFoundSpices());	
end

rule "Korisnik je izabrao Italijanksku kuhinju i zasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Italijanska", sweetenedIcedTea =="Da" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SLATKO);
		System.out.println("Vino je SLATKOOOO: " + $f.getFoundSugar());	
end

rule "Korisnik je izabrao Italijanksku kuhinju i nezasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Italijanska", sweetenedIcedTea =="Ne" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SUVO);
		System.out.println("Vino je sad SUVOOOO: " + $f.getFoundSugar());	
end

//Pravilo gde trazimo vino koje sadrzi sve sastojke!!!!

rule "Trazimo vino "
	agenda-group "prva_grupa_pravila"	
	salience -10
	when
		$f: Found()
		$w: Wine(wineSugar == $f.getFoundSugar())
		eval($w.containsMeatWithName($f.getFoundMeat()))
		eval($w.containsSauceWithName($f.getFoundSauce()))
		eval($w.containsSpiceWithName($f.getFoundSpices()))
		
	then
		drools.getKnowledgeRuntime().setGlobal("foundWine", $w);
		System.out.println("Nasli smo vinoo: "+ $w.getName());
end




//Pravila za Francusku kuhinju

rule "Korisnik je izabrao Francusku kuhinju i narucuje desert"
	agenda-group "prva_grupa_pravila"
	when
		$a:Answers(ethnicity == "Francuska", haveDessert == "Da")
		$w: Wine(name == "Riesling" )
	then
		$w.setDessert(true);	
		System.out.println("Korisnik narucuje desert "+ $w.getName());
		drools.getKnowledgeRuntime().setGlobal("foundWine", $w);
end

rule "Korisnik izabrao Francusku kuhinju i trenira"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Francuska", healthConscious == "Da")
		$m: Meat(name == "Jastog")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());

end	

rule "Korisnik je izabarao Francusku  kuhinju,  NE trenira i jesen je ili zima"
	agenda-group "prva_grupa_pravila"
	salience 100  
	when
		$a:Answers(ethnicity == "Francuska", healthConscious == "Ne", autmnOrWinter == "Da")
		
	then
		Found f = new Found();
		f.setFoundMeat("Divljac");
		insert(f);
		System.out.println("Meso je: " + f.getFoundMeat());
		
end

rule "Korisnik je izabarao Francusku  kuhinju, trenira i NIJE jesen ili zima"
	agenda-group "prva_grupa_pravila"
	salience 100  
	when
		$a:Answers(ethnicity == "Francuska", healthConscious == "Ne", autmnOrWinter == "Ne")
		
	then
		Found f = new Found();
		f.setFoundMeat("Teletina");
		insert(f);
		System.out.println("Meso je: " + f.getFoundMeat());
		
end

rule "Korisnik je izabrao Francusku  kuhinju,alergican je na neku hranu i intolerantan na laktozu "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Francuska", foodAllergy == "Da",lactoseIntolerant == "Da")
		$f: Found()
		
	then
		$f.setFoundSauce("Senf");
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Francusku  kuhinju,alergican je na neku hranu i NIJE intolerantan na laktozu "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Francuska", foodAllergy == "Da",lactoseIntolerant == "Ne")
		$f: Found()
		
	then
		$f.setFoundSauce("Sir");
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Francusku  kuhinju, NIJE alergican  na neku hranu"
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Francuska", foodAllergy == "Ne")
		$f: Found()
		
	then
		$f.setFoundSauce("Pecurke");
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Francusku kuhinju i voli zacinjenu hranu"
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Francuska", savoryFood == "Da")
		$f: Found()
		
	then
		$f.getFoundSpices().add("Biber u zrnu");
		$f.getFoundSpices().add("Muskatni orascic");
		System.out.println("Lista zacina iz pravila izmenjeno: " + $f.getFoundSpices());
end


rule "Korisnik je izabrao Francusku kuhinju i ne ide na dejt "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Francuska", onDate =="Ne" )
		$f: Found()
		
	then
		$f.getFoundSpices().add("Mladi luk");
		System.out.println("Lista zacina kad ne ide na dejt: " + $f.getFoundSpices());	
end

rule "Korisnik je izabrao Francusku kuhinju i zasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Francuska", sweetenedIcedTea =="Da" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SLATKO);
		System.out.println("Vino je SLATKOOOO: " + $f.getFoundSugar());	
end

rule "Korisnik je izabrao Francusku kuhinju i nezasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Francuska", sweetenedIcedTea =="Ne" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SUVO);
		System.out.println("Vino je sad SUVOOOO: " + $f.getFoundSugar());	
end




//Pravila za Indijsku  kuhinju

rule "Korisnik je izabrao Indijsku kuhinju i narucuje desert"
	agenda-group "prva_grupa_pravila"
	when
		$a:Answers(ethnicity == "Indijska", haveDessert == "Da")
		$w: Wine(name == "Riesling" )
	then	
		$w.setDessert(true);
		System.out.println("Korisnik narucuje desert "+ $w.getName());
		drools.getKnowledgeRuntime().setGlobal("foundWine", $w);
end

rule "Korisnik izabrao Indijsku kuhinju,trenira i preferira obroke bogate proteinima iz mesa"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Indijska", healthConscious == "Da", preferMeat == "Da")
		$m: Meat(name == "Kozije meso")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());

end	

rule "Korisnik je izabarao Indijsku  kuhinju,  NE trenira"
	agenda-group "prva_grupa_pravila"
	salience 100  
	when
		$a:Answers(ethnicity == "Indijska", healthConscious == "Ne")
		$m: Meat(name == "Jagnjetina mlevena")
		
	then
		Found f = new Found();
		f.setFoundMeat($m.getName());
		insert(f);
		System.out.println("Meso je: " + f.getFoundMeat());
		
end


rule "Korisnik je izabrao Indijsku  kuhinju,alergican je na neku hranu i voli kremaste ukuse "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Indijska", foodAllergy == "Da", creamyFlavors == "Da")
		$s: Sauce(name == "Jogurt")
		$f: Found()
		
	then
		$f.setFoundSauce($s.getName());
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Indijsku  kuhinju,alergican je na neku hranu i NE VOLI kreamaste ukuse "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Indijska", foodAllergy == "Da", creamyFlavors == "Ne")
		$s: Sauce(name == "Paradajz")
		$f: Found()
		
	then
		$f.setFoundSauce($s.getName());
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Indijsku kuhinju, NIJE alergican  na neku hranu"
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Indijska", foodAllergy == "Ne")
		$s: Sauce(name == "Indijski orah")
		$f: Found()
		
	then
		$f.setFoundSauce($s.getName());
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end


rule "Korisnik je izabrao Indijsku kuhinju i voli da jela imaju izrazene ukuse i arome"
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Indijska", savoryFood == "Da")
		$f: Found()
		
	then
		$f.getFoundSpices().add("Kari");
		$f.getFoundSpices().add("Limeta");
		$f.getFoundSpices().add("Nana");
		System.out.println("Lista zacina kada voli zacinjenu hranu: " + $f.getFoundSpices());
end

rule "Korisnik je izabrao Indijsku kuhinju i NE VOLI da jela imaju izrazene ukuse i arome"
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Indijska", savoryFood == "Ne")
		$f: Found()
		
	then
		$f.getFoundSpices().add("Kurkuma");
		$f.getFoundSpices().add("Zvezdasti anis");
		System.out.println("Lista zacina kada NE VOLI zacinjenu hranu: " + $f.getFoundSpices());
end

rule "Korisnik je izabrao Indijsku kuhinju i NE ide na dejt "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Indijska", onDate =="Ne" )
		$f: Found()
		
	then
		$f.getFoundSpices().add("Beli luk u prahu");
		System.out.println("Lista zacina kad ne ide na dejt: " + $f.getFoundSpices());	
end


rule "Korisnik je izabrao Indijsku kuhinju i zasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Indijska", sweetenedIcedTea =="Da" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SLATKO);
		System.out.println("Vino je SLATKOOOO: " + $f.getFoundSugar());	
end

rule "Korisnik je izabrao Indijsku kuhinju i nezasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Indijska", sweetenedIcedTea =="Ne" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SUVO);
		System.out.println("Vino je sad SUVOOOO: " + $f.getFoundSugar());	
end



//Pravila za Americku kuhinju

rule "Korisnik je izabrao Americku kuhinju i narucuje desert"
	agenda-group "prva_grupa_pravila"
	when
		$a:Answers(ethnicity == "Americka", haveDessert == "Da")
		$w: Wine(name == "Riesling" )
	then
		$w.setDessert(true);	
		System.out.println("Korisnik narucuje desert "+ $w.getName());
		drools.getKnowledgeRuntime().setGlobal("foundWine", $w);
end

rule "Korisnik izabrao Americku kuhinju, trenira"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Americka", healthConscious == "Da")
		$m: Meat(name == "Curetina")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());

end	

rule "Korisnik izabrao Americku kuhinju, NE trenira i preferira jela poznata po bokatom ukusu i socnosti"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Americka", healthConscious == "Ne", juicyDishes == "Da")
		$m: Meat(name == "Govedina")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());

end	

rule "Korisnik izabrao Americku kuhinju, NE trenira i NE preferira jela poznata po bokatom ukusu i socnosti"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Americka", healthConscious == "Ne", juicyDishes == "Ne")
		$m: Meat(name == "Svinjetina")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());

end	

rule "Korisnik je izabrao Americku kuhinju i voli pizzu sa ananasom "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Americka", pizzaWithPineapple == "Da")
		$s: Sauce(name == "Med")
		$f: Found()
		
	then
		$f.setFoundSauce($s.getName());
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Americku kuhinju i NE voli pizzu sa ananasom "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Americka", pizzaWithPineapple == "Ne")
		$s: Sauce(name == "BBQ sos")
		$f: Found()
		
	then
		$f.setFoundSauce($s.getName());
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Americku kuhinju i voli da jela koja imaju pikantan ukus"
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Americka", spicyFood == "Da")
		$f: Found()
		
	then
		$f.getFoundSpices().add("Paprika");
		System.out.println("Lista zacina kada voli zaljucenu hranu: " + $f.getFoundSpices());
end

rule "Korisnik je izabrao Americku kuhinju i NE VOLI da jela koja imaju pikantan ukus"
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Americka", spicyFood== "Ne")
		$f: Found()
		
	then
		$f.getFoundSpices().add("Cimet");
		System.out.println("Lista zacina kada NE VOLI zaljucenu hranu: " + $f.getFoundSpices());
end

rule "Korisnik je izabrao Americku kuhinju i NE ide na dejt "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Americka", onDate =="Ne" )
		$f: Found()
		
	then
		$f.getFoundSpices().add("Crni luk");
		System.out.println("Lista zacina kad ne ide na dejt: " + $f.getFoundSpices());	
end

rule "Korisnik je izabrao Americku kuhinju i zasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Americka", sweetenedIcedTea =="Da" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SLATKO);
		System.out.println("Vino je SLATKOOOO: " + $f.getFoundSugar());	
end

rule "Korisnik je izabrao Americku kuhinju i nezasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Americka", sweetenedIcedTea == "Ne" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SUVO);
		System.out.println("Vino je sad SUVOOOO: " + $f.getFoundSugar());	
end




//Pravila za Kinesku kuhinju

rule "Korisnik je izabrao Kinesku kuhinju i narucuje desert"
	agenda-group "prva_grupa_pravila"
	when
		$a:Answers(ethnicity == "Kineska", haveDessert == "Da")
		$w: Wine(name == "Riesling" )
	then
		$w.setDessert(true);	
		System.out.println("Korisnik narucuje desert "+ $w.getName());
		drools.getKnowledgeRuntime().setGlobal("foundWine", $w);
end

rule "Korisnik izabrao Kinesku kuhinju, trenira i preferira osveavajuce ukuse koji podsecaju na more"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Kineska", healthConscious == "Da", refreshingFlavors == "Da")
		$m: Meat(name == "Riba")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());

end	

rule "Korisnik izabrao Kinesku kuhinju, trenira i NE preferira osvezavajuce ukuse koji podsecaju na more"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Kineska", healthConscious == "Da", refreshingFlavors == "Ne")
		$m: Meat(name == "Belo meso")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());

end

rule "Korisnik izabrao Kinesku kuhinju i NE trenira"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Kineska", healthConscious == "Ne")
		$m: Meat(name == "Patka")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());
end		

rule "Korisnik je izabrao Kinesku kuhinju i voli pizzu sa ananasom "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Kineska", pizzaWithPineapple == "Da")
		$s: Sauce(name == "Slatko-kiseli sos")
		$f: Found()
		
	then
		$f.setFoundSauce($s.getName());
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Kinesku kuhinju i NE voli pizzu sa ananasom "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Kineska", pizzaWithPineapple == "Ne")
		$s: Sauce(name == "Terijaki sos")
		$f: Found()
		
	then
		$f.setFoundSauce($s.getName());
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end


rule "Korisnik je izabrao Kinesku kuhinju i voli da jela koja imaju pikantan ukus"
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Kineska", spicyFood == "Da")
		$f: Found()
		
	then
		$f.getFoundSpices().add("Cili paprike");
		$f.getFoundSpices().add("Prah 5 zacina");
		System.out.println("Lista zacina kada voli zaljucenu hranu: " + $f.getFoundSpices());
end

rule "Korisnik je izabrao Kinesku kuhinju i NE VOLI da jela koja imaju pikantan ukus"
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Kineska", spicyFood== "Ne")
		$f: Found()
		
	then
		$f.getFoundSpices().add("Korijander");
		$f.getFoundSpices().add("Ulje od susama");
		$f.getFoundSpices().add("Koren djumbira");
		System.out.println("Lista zacina kada NE VOLI zaljucenu hranu: " + $f.getFoundSpices());
end


rule "Korisnik je izabrao Kinesku kuhinju i zasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Kineska", sweetenedIcedTea =="Da" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SLATKO);
		System.out.println("Vino je SLATKOOOO: " + $f.getFoundSugar());	
end

rule "Korisnik je izabrao Kinesku kuhinju i nezasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Kineska", sweetenedIcedTea == "Ne" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SUVO);
		System.out.println("Vino je sad SUVOOOO: " + $f.getFoundSugar());	
end




//Pravila za Meksicku kuhinju

rule "Korisnik je izabrao Meksicku kuhinju i narucuje desert"
	agenda-group "prva_grupa_pravila"
	when
		$a:Answers(ethnicity == "Meksicka", haveDessert == "Da")
		$w: Wine(name == "Riesling" )
	then	
		$w.setDessert(true);
		System.out.println("Korisnik narucuje desert "+ $w.getName());
		drools.getKnowledgeRuntime().setGlobal("foundWine", $w);
end

rule "Korisnik izabrao Meksicku kuhinju, NE trenira i preferira bogate, dimljene ukuse"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Meksicka", healthConscious == "Ne", smokyFlavors == "Da")
		$m: Meat(name == "Jelen")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());

end	

rule "Korisnik izabrao Meksicku kuhinju, NE trenira i NE preferira bogate dimljene ukuse"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Meksicka", healthConscious == "Ne", smokyFlavors == "Ne")
		$m: Meat(name == "Svinjska kobasica")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());

end

rule "Korisnik izabrao Meksicku kuhinju i trenira"
	agenda-group "prva_grupa_pravila"
	salience 100
	when
		$a:Answers(ethnicity == "Meksicka", healthConscious == "Da")
		$m: Meat(name == "Pavo")
		
	then
		Found found = new Found();
		found.setFoundMeat($m.getName());
		insert(found);
		System.out.println("Meso je: "+ found.getFoundMeat());
end		

rule "Korisnik je izabrao Meksicku kuhinju i kremaste ukuse i intolerantan je na laktozu "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Meksicka", creamyFlavors == "Da", lactoseIntolerant == "Da")
		$s: Sauce(name == "Avokado")
		$f: Found()
		
	then
		$f.setFoundSauce($s.getName());
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Meksicku kuhinju i kremaste ukuse i NIJE intolerantan je na laktozu "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Meksicka", creamyFlavors == "Da", lactoseIntolerant == "Ne")
		$s: Sauce(name == "Crema Mexicana")
		$f: Found()
		
	then
		$f.setFoundSauce($s.getName());
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Meksicku kuhinju i NE preferira kremaste ukuse  "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Meksicka", creamyFlavors == "Ne")
		$s: Sauce(name == "Tomatillo")
		$f: Found()
		
	then
		$f.setFoundSauce($s.getName());
		System.out.println("Sosic  je: " +$f.getFoundSauce());
end

rule "Korisnik je izabrao Meksicku kuhinju i preferira ljutu hranu"
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Meksicka", spicyFood == "Da")
		$f: Found()
		
	then
		$f.getFoundSpices().add("Ljute papricice");
		$f.getFoundSpices().add("Kumin");
		$f.getFoundSpices().add("Persun");
		System.out.println("Lista zacina kada voli zaljucenu hranu: " + $f.getFoundSpices());
end

rule "Korisnik je izabrao Meksicku  kuhinju i NE preferira ljutu hranu"
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Meksicka", spicyFood== "Ne")
		$f: Found()
		
	then
		$f.getFoundSpices().add("Slatka paprika");
		$f.getFoundSpices().add("Suseni paradajz");
		System.out.println("Lista zacina kada NE VOLI zaljucenu hranu: " + $f.getFoundSpices());
end


rule "Korisnik je izabrao Meksicku kuhinju i zasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Meksicka", sweetenedIcedTea =="Da" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SLATKO);
		System.out.println("Vino je SLATKOOOO: " + $f.getFoundSugar());	
end

rule "Korisnik je izabrao Meksicku kuhinju i nezasladjeni IceTea "
	agenda-group "prva_grupa_pravila"
	when
		$a: Answers(ethnicity == "Meksicka", sweetenedIcedTea == "Ne" )
		$f: Found()
		
	then
		$f.setFoundSugar(WineSugar.SUVO);
		System.out.println("Vino je sad SUVOOOO: " + $f.getFoundSugar());	
end